### ISSUE TITLE
TS2507: Type 'typeof EventEmitter' is not a constructor function type.

### ISSUE THREAD

**Issue by nikolaymatrosov** [yandex-cloud/ydb-nodejs-sdk#31]
**ydb-sdk/build/table.d.ts**
```
Error:(43, 38) TS2507: Type 'typeof EventEmitter' is not a constructor function type.
Error:(66, 42) TS2507: Type 'typeof EventEmitter' is not a constructor function type.
Error:(87, 42) TS2507: Type 'typeof EventEmitter' is not a constructor function type.
```
Maybe you mean `EventEmitter. EventEmitter`?

**Comment by tsufiev** [comment]
@nikolaymatrosov that's weird! Could you please elaborate, how did you get this error?

**Comment by nikolaymatrosov** [comment]
Nevermind. I can not replicate the error today. Maybe the problem was in the incompatible `@types/node` package. It seems it was rewritten between 12 and 13 node versions.
