### ISSUE TITLE
Make camel-casing of property names optional

### ISSUE THREAD

**Issue by IlyaSemenov** [yandex-cloud/ydb-nodejs-sdk#71]
Here:

https://github.com/yandex-cloud/ydb-nodejs-sdk/blob/a1cc0fc0ac4c9677b62fa69ce5733b0b91d3c09e/src/types.ts#L284

you explicitly camel-case TypedData object properties. This is very counter-intuitive and breaks things. What if I **do** want to use snake_cased properties in my models? How come the library doesn't even allow me to do that? It should be agnostic to naming conventions. For those who want that conversion, you can provide a static meta property or something else.

**Comment by vitalets** [comment]
Agree.

**Comment by nikolaymatrosov** [comment]
Changing this behavior would be a breaking change. Somebody already relies on it. It would be a better option to provide additional config in the `declareType` decorator, so the user of the SDK could decide how he wants to map names.

**Comment by IlyaSemenov** [comment]
I don't see anything wrong in breaking changes. If someone is relying on the old behaviour, she may continue to do so with the old library version. Should they decide to upgrade to the next major release, they will need to adapt (enable camel-casing with some kind of option) — but that's what always happens.

Ultimately the library should be providing reasonable defaults, and auto-converting names is not exactly reasonable. Could you name any major ORM that does the conversion by default? For instance:
* objection.js: [it's optional and not enabled by default](https://vincit.github.io/objection.js/recipes/snake-case-to-camel-case-conversion.html)
* sequelize: [auto-converting is optional and not enabled by default](https://sequelize.org/master/manual/naming-strategies.html)
* TypeORM: [auto-converting is optional and not enabled by default](https://www.npmjs.com/package/typeorm-naming-strategies)

**Comment by tsufiev** [comment]
I agree with your points, looking into a way to make the behaviour you want optional in the next minor version, then make it default in the next major release.

**Comment by tsufiev** [comment]
@IlyaSemenov please take a look at https://github.com/yandex-cloud/ydb-nodejs-sdk/pull/76
